# SPDX-FileCopyrightText: 2024 blinry <mail@blinry.org>
# SPDX-FileCopyrightText: 2024 zormit <nt4u@kpvn.de>
#
# SPDX-License-Identifier: CC-BY-SA-4.0

[book]
authors = ["blinry", "zormit"]
language = "en"
multilingual = false
src = "src"
title = "Teamtype Documentation"

[output.html]
site-url = "/teamtype/"
