# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Mirror development version of Neovim plugin

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nvim-plugin/**'
      - '.github/workflows/deploy-nvim-plugin.yml'

# There's a "mirror to main" step in release.yml, make sure to change both accordingly.
jobs:
  mirror:
    name: Mirror to ethersync/ethersync-nvim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:ethersync/ethersync-nvim
          BRANCH: develop
          FOLDER: nvim-plugin
          SSH_PRIVATE_KEY: ${{ secrets.NVIM_PLUGIN_DEPLOY_PRIVATE_KEY }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: "Automatic mirror of commit {sha} in main Ethersync repository"
