# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Deploy Vim plugin

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nvim-plugin/**'
      - '.github/workflows/deploy-vim-plugin.yml'

jobs:
  mirror:
    name: Mirror to ethersync/ethersync-vim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:ethersync/ethersync-vim
          BRANCH: main
          FOLDER: nvim-plugin
          SSH_PRIVATE_KEY: ${{ secrets.VIM_PLUGIN_DEPLOY_PRIVATE_KEY }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: "Automatic mirror of commit {sha} in main Ethersync repository"
