# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Nix

on:
  push:
    branches:
      - 'main'
    paths:
      - 'flake.*'
      - 'contrib/nix/**'
      - 'daemon/**'
      - 'nvim-plugin/**'
      - '.github/workflows/nix.yml'
  pull_request:
    paths:
      - 'flake.*'
      - 'contrib/nix/**'
      - 'daemon/**'
      - 'nvim-plugin/**'
      - '.github/workflows/nix.yml'

jobs:
  check_nix:
    name: Check Nix code
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Evaluate Nix code
        run: nix -Lv flake check
      - name: Build Neovim with Ethersync
        run: nix -Lv build .#neovim
      - run: result/bin/nvim --version
