# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Vim plugin

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nvim-plugin/**'
      - '.github/workflows/vim-plugin.yml'
  pull_request:
    paths:
      - 'nvim-plugin/**'
      - '.github/workflows/vim-plugin.yml'

jobs:
  check_lua:
    name: Check Lua formatting and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --config-path nvim-plugin/.stylua.toml --check nvim-plugin
      - name: Luacheck Linting
        uses: lunarmodules/luacheck@v1
        with:
          args: --config nvim-plugin/.luacheckrc nvim-plugin
